### ISSUE TITLE
Please add a license and a screen shot

### ISSUE THREAD

**Issue by unixorn** [kostoskistefan/scythe#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by kostoskistefan** [comment]
Hey!

I don't know why I didn't think that people might find this useful and I only added it to Github as a personal project, but it would be a pleasure to contribute to your awesome list. I'll add screenshots and a license in a few minutes.

Thanks for reaching out!

**Comment by unixorn** [comment]
Cool. Ping me on this issue when you're done and I'll add it or you can directly PR it into the list if you prefer.

**Comment by kostoskistefan** [comment]
@unixorn I've added the license and a few screenshots. I think they are sufficient, since it's quite a minimal theme. Thanks again for contacting me!
